### ISSUE TITLE
Doesn't work with Angular AOT

### ISSUE THREAD

**Issue by emolr** [gjuchault/ng2-storeService#1]
<img width="1198" alt="screen shot 2016-11-23 at 13 26 37" src="https://cloud.githubusercontent.com/assets/2789549/20549472/9313bb92-b180-11e6-9969-695593f8300e.png">

What i have found is that:

`type Transformer` is private, causing an typescript error. 
But i tried making it any so it would be a problem, but it didn't change anything. the error of 
`Supplied parameters do not match any signature of call target` persists

I have learned that AOT is extremely strict on types and errors

**Comment by gjuchault** [comment]
Do you think by exporting it (there is no way to make something public when it's not inside a class) that would work ?

**Comment by gjuchault** [comment]
Fixed in last relase :)
