### ISSUE TITLE
Full example request

### ISSUE THREAD

**Issue by st-clair-clarke** [gjuchault/ng2-storeService#2]
Hi, 
I am new tow ngrx/store etc. Could you please put the reducer example in the README? Or maybe a simple comprehensive example on your site would still be better.

Thanks

**Comment by gjuchault** [comment]
Hi,

If you are new to ngrx, then this should not be what you seek. It's a simple wrapper over ngrx/store to add the possibility to transform every request you make to the store — to use Immutable or others. Full example of ngrx/store can be found in their readme :)
